/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate health, for a human or an alert
         * @description Always answers 200: it is informational, and a 503 here would look to a monitor like the
         *     endpoint itself being down. The meaning is in the body.
         *
         *     Without the service token the body is `HealthSummary` — one field. With it, `HealthDetail`
         *     adds `ready` and the per-check breakdown. Dependency names describe what the system is
         *     built from, which is why an anonymous caller does not get them (ADR-055).
         */
        get: operations["healthAggregate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the process alive
         * @description Consults no dependency, by construction — the handler is not given the reporter. A liveness
         *     probe that checked a dependency would turn that dependency's outage into a restart loop of
         *     a healthy process.
         *
         *     Answers 200 with `{"status":"up"}` whenever it answers at all. A dead process does not
         *     answer, which is the signal.
         */
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Should traffic come here
         * @description Readiness follows `required_for_readiness` on each check rather than the aggregate status,
         *     so a `degraded` application answers **200**: an unavailable optional dependency must not
         *     close the part of the product that does not need it.
         *
         *     503 rather than 500 when unready — "not now, try later" is the statement being made.
         */
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether identity routes are available */
        get: operations["authStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start a CSRF-protected browser session */
        get: operations["authCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured browser sign-in providers */
        get: operations["authProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin a Google Authorization Code + PKCE sign-in */
        get: operations["startGoogleOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Google state, exchange the code, and issue a session */
        get: operations["finishGoogleOAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/link/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthenticate and begin explicitly linking a Google account */
        post: operations["startGoogleAccountLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/reauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reauthenticate the current account with its already-linked Google identity */
        get: operations["startGoogleReauthentication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/account/reauth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a password proof for the current session for five minutes */
        post: operations["reauthenticateWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/unlink": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthenticate and unlink Google when another sign-in method remains */
        post: operations["unlinkGoogleAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read whether the current account has Google linked */
        get: operations["googleAccountLinkStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a new account's email with a registration-bound code
         * @default {
         *       "$ref": "#/components/responses/Problem"
         *     }
         */
        post: operations["verifyRegistrationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a registration code again without confirming account existence */
        post: operations["resendRegistrationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/email/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a purpose-bound email sign-in code */
        post: operations["requestEmailSignInCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an email sign-in code and continue the server-selected sign-in policy */
        post: operations["completeEmailSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request an account-neutral password reset code */
        post: operations["requestPasswordResetCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace or add a password after verifying a reset-purpose code */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the signed-in user's password after re-entering the current password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a verified account's password */
        post: operations["signInWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and send its registration-bound email code */
        post: operations["registerWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a pending sign-in with an enrolled second factor */
        post: operations["verifySignInSecondFactor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin authenticator enrollment for the signed-in account */
        post: operations["beginSecondFactorEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm enrollment by verifying a code from the selected method */
        post: operations["confirmSecondFactorEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current account's enrolled factors and recent verification state */
        get: operations["readSecondFactorStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove an enrolled factor after recent reauthentication and explicit confirmation */
        post: operations["disableSecondFactor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/backup-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace recovery codes after confirming the current password */
        post: operations["replaceBackupCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/email/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a purpose-bound email factor code for a pending sign-in */
        post: operations["requestSignInEmailMfaCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/email/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reauthenticate and send an email factor enrollment code */
        post: operations["beginEmailMfaEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the email factor enrollment challenge */
        post: operations["confirmEmailMfaEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/required/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin a factor enrollment using the scoped sign-in challenge */
        post: operations["beginRequiredMfaEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/required/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm required factor enrollment and complete sign-in */
        post: operations["confirmRequiredMfaEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/admin/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current ready-made authentication policy */
        get: operations["readAuthenticationPolicy"];
        /** Save a policy using optimistic version checking */
        put: operations["updateAuthenticationPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/admin/mfa/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke an account's MFA methods, sessions, and in-progress sign-ins */
        post: operations["resetAccountMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token and issue a new access token */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session and clear its cookies */
        post: operations["signOutCurrentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every session for the signed-in account */
        post: operations["signOutAllSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sessions belonging to the signed-in account */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one session belonging to the signed-in account */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignInResult: {
            /** @enum {string} */
            status: "issued" | "requires_second_factor" | "requires_enrollment";
            /** Format: uuid */
            pending_id?: string;
            /** @description Enrolled factors for MFA, or factors that can satisfy a required enrollment. */
            available_methods?: ("TOTP" | "EMAIL_OTP" | "BACKUP_CODE")[];
            /** @enum {string} */
            primary_method?: "PASSWORD" | "GOOGLE" | "EMAIL_CODE";
        };
        /**
         * @description Three states, not two. `degraded` means working with something missing — the distinction
         *     exists so that an unavailable optional dependency does not read as an outage.
         * @enum {string}
         */
        HealthStatus: "up" | "degraded" | "down";
        /**
         * @description What an unauthorised caller gets. One field, and a separate schema from `HealthDetail`
         *     rather than a filtered view of it: a shape with one field cannot leak a second.
         */
        HealthSummary: {
            status: components["schemas"]["HealthStatus"];
        };
        HealthDetail: {
            status: components["schemas"]["HealthStatus"];
            /**
             * @description Kept although it is derivable from the checks, because the derivation is not obvious —
             *     a `down` optional dependency leaves the application ready — and making a reader redo
             *     that logic invites getting it wrong.
             */
            ready: boolean;
            checks: components["schemas"]["HealthChecked"][];
        };
        HealthChecked: {
            /**
             * @description Stable across releases, because alert rules reference it.
             * @example database
             * @example schema
             */
            name: string;
            status: components["schemas"]["HealthStatus"];
            /** @description Whole milliseconds, so an alert threshold reads `3` rather than `0.003`. */
            took_ms: number;
            cause?: components["schemas"]["HealthCause"];
        };
        /**
         * @description Why a check is not `up`, discriminated by `kind` — not `type`, because `threw` already has
         *     a field of that name and §11.6 spends `type` on a problem URI.
         *
         *     Two internal causes have no representation here at all: an aggregate over ailing
         *     dependencies, and a schema behind the code. Both name what the system is made of, and
         *     ADR-055 withholds that from every answer including an authorised one.
         */
        HealthCause: components["schemas"]["CauseRefused"] | components["schemas"]["CauseOverran"] | components["schemas"]["CauseThrew"];
        CauseRefused: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "refused";
            /** @description The check's own words. The one cause whose text we write rather than a library. */
            says: string;
        };
        CauseOverran: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "overran";
            /** @description The bound the check did not answer inside. */
            bound_ms: number;
        };
        CauseThrew: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "threw";
            /**
             * @description The exception's type and nothing else. A message carries hosts, ports and occasionally
             *     credentials (§17), so there is no field for one.
             * @example SQLException
             */
            type: string;
        };
        AuthenticationPolicyRule: {
            /** @enum {string} */
            primary: "PASSWORD" | "GOOGLE" | "EMAIL_CODE";
            enabled: boolean;
            /** @enum {string} */
            requirement: "DISABLED" | "IF_ENROLLED" | "REQUIRED";
            allowed_methods: ("TOTP" | "EMAIL_OTP" | "BACKUP_CODE")[];
        };
        AuthenticationPolicy: {
            version: number;
            rules: components["schemas"]["AuthenticationPolicyRule"][];
            advanced_acknowledged: boolean;
        };
        UpdateAuthenticationPolicy: {
            expected_version: number;
            rules: components["schemas"]["AuthenticationPolicyRule"][];
            advanced_acknowledged: boolean;
        };
        Problem: {
            /**
             * Format: uri
             * @description Stable identifier of the *kind* of failure, and the field a client branches on. It
             *     survives rewording of `title` and `detail`.
             *
             *     `about:blank` means what RFC 9457 section 4.2.1 says it means: the failure has no
             *     semantics beyond its status code, and `title` is that code's own phrase. It is what a
             *     status the server produced without reaching any endpoint carries — an unknown path, a
             *     method an endpoint does not accept. A client telling "no such resource" apart from "no
             *     such address" branches on this field, which is the reason it is not one value for both.
             * @example https://tallyvane.com/errors/validation-failed
             * @example https://tallyvane.com/errors/malformed-request
             * @example https://tallyvane.com/errors/internal
             * @example about:blank
             */
            type: string;
            /** @description The kind in human words, identical for every occurrence of one `type`. */
            title: string;
            /** @description Repeated in the body so the document stands alone when forwarded or logged. */
            status: number;
            /** @description This occurrence in human words. Never a driver's message. */
            detail?: string;
            /** @description Per-field detail for a validation failure; absent otherwise. */
            errors?: components["schemas"]["FieldError"][];
            /**
             * @description Added by the renderer, so it is on every problem body including a 500. The same id is
             *     in the `traceparent` header and on the log lines of that request.
             */
            trace_id?: string;
        };
        FieldError: {
            /** @description The name as the client sent it — `salary_min_cents`, not `salaryMinCents`. */
            field: string;
            /**
             * @description What is wrong, in a form a frontend can branch on. A free string on purpose: closing
             *     this set would put every module's validation vocabulary in the platform.
             * @example range.invalid
             * @example required
             */
            code: string;
        };
    };
    responses: {
        /**
         * @description Any failure, in one shape (§11.6, RFC 9457). A route never invents a status or a `type`:
         *     both come from a closed set in the platform, so a client can branch on `type` and expect
         *     it to stay put (ADR-062).
         *
         *     This includes the statuses the server produces before any endpoint is reached — an unknown
         *     path, a method an endpoint does not accept. Those carry `about:blank` and no `detail`, and
         *     they are not listed per operation below, because they are not any one operation's answer.
         */
        Problem: {
            headers: {
                traceparent: components["headers"]["Traceparent"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /**
         * @description Always `no-store`. Cloudflare sits in front of this application, and a 200 with no cache
         *     directives is a legitimate thing to cache — after which a cheerful "up" would outlive the
         *     truth.
         */
        NoStore: "no-store";
        /**
         * @description W3C Trace Context. Present on every response, including ones with no body. Quote it when
         *     reporting a problem: the same id is on the log lines of that request.
         */
        Traceparent: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthAggregate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The aggregate. Shape depends on whether the service token was accepted. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    traceparent: components["headers"]["Traceparent"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"] | components["schemas"]["HealthDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is answering. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    traceparent: components["headers"]["Traceparent"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready for traffic. May still be `degraded`. */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    traceparent: components["headers"]["Traceparent"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
            /** @description A dependency required for readiness is down. */
            503: {
                headers: {
                    "Cache-Control": components["headers"]["NoStore"];
                    traceparent: components["headers"]["Traceparent"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummary"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    authStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity API status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "available";
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    authCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a one-use-per-request double-submit token and sets an HttpOnly cookie. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    authProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider availability for this server deployment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        google: boolean;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    startGoogleOAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to Google and sets short-lived HttpOnly state and verifier cookies. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    finishGoogleOAuth: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to the app, setting session cookies only after a verified callback. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    startGoogleAccountLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Google authorization URL for the account-link flow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    startGoogleReauthentication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to Google and returns to account security after verifying the linked OIDC subject. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    reauthenticateWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description The active session now has a recent reauthentication proof. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    unlinkGoogleAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description The Google sign-in method was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account would have no usable sign-in method. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    googleAccountLinkStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current account's Google link state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        google_linked: boolean;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    verifyRegistrationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    challenge_id: string;
                    /** Format: email */
                    email: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description The address is verified. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The challenge was invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resendRegistrationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description A neutral response; challenge_id is null when no new code was issued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        challenge_id: string | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    requestEmailSignInCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Code request accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        challenge_id: string;
                    };
                };
            };
            /** @description A code was requested recently; retry after the Retry-After delay. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    completeEmailSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    challenge_id: string;
                    /** Format: email */
                    email: string;
                    code: string;
                    device: string;
                };
            };
        };
        responses: {
            /** @description Session cookies were issued or the next server-selected authentication step is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    requestPasswordResetCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Request accepted without revealing whether the address has an account. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        challenge_id: string;
                    };
                };
            };
            /** @description A reset code was requested recently. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    challenge_id: string;
                    /** Format: email */
                    email: string;
                    code: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Request completed with an account-neutral response. Existing MFA stays enabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "completed";
                    };
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    current_password: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password changed. Existing second factors remain enabled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    signInWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    device: string;
                };
            };
        };
        responses: {
            /** @description Session cookies were issued or the next server-selected authentication step is returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    registerWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    display_name?: string | null;
                };
            };
        };
        responses: {
            /** @description Account created; challenge_id may be null if email delivery is unavailable. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        user_id: string;
                        /** Format: uuid */
                        challenge_id: string | null;
                    };
                };
            };
            /** @description Account email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    verifySignInSecondFactor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    pending_id: string;
                    kind: string;
                    code: string;
                    /**
                     * Format: uuid
                     * @description Required when kind is EMAIL_OTP.
                     */
                    challenge_id?: string;
                };
            };
        };
        responses: {
            /** @description Session issued after factor verification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    beginSecondFactorEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kind: string;
                };
            };
        };
        responses: {
            /** @description Enrollment payload for the selected method. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    confirmSecondFactorEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kind: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Factor enrollment confirmed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    readSecondFactorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrolled factors and whether this session was reauthenticated during the last five minutes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        enrolled: ("TOTP" | "EMAIL_OTP" | "BACKUP_CODE")[];
                        recently_authenticated: boolean;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    disableSecondFactor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "TOTP" | "EMAIL_OTP" | "BACKUP_CODE";
                    /** @constant */
                    confirmed: true;
                };
            };
        };
        responses: {
            /** @description The selected factor was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The session needs recent reauthentication. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Removing the factor would make a required sign-in scheme unusable. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    replaceBackupCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    current_password: string;
                };
            };
        };
        responses: {
            /** @description New one-time-display recovery codes. Response is marked no-store. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        codes: string[];
                    };
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    requestSignInEmailMfaCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    pending_id: string;
                };
            };
        };
        responses: {
            /** @description Code accepted for delivery; response includes challenge_id. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    beginEmailMfaEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    current_password: string;
                };
            };
        };
        responses: {
            /** @description Enrollment code accepted for delivery; response includes challenge_id. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    confirmEmailMfaEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    challenge_id: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Email factor enrollment confirmed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    beginRequiredMfaEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    pending_id: string;
                    /** @enum {string} */
                    kind: "TOTP";
                };
            };
        };
        responses: {
            /** @description Enrollment payload for the selected factor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    confirmRequiredMfaEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    pending_id: string;
                    /** @enum {string} */
                    kind: "TOTP";
                    code: string;
                };
            };
        };
        responses: {
            /** @description Enrollment accepted and session cookies issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    readAuthenticationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned policy rules captured by new sign-in attempts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationPolicy"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateAuthenticationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAuthenticationPolicy"];
            };
        };
        responses: {
            /** @description The saved policy with its incremented version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationPolicy"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    resetAccountMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @constant */
                    confirmation: true;
                };
            };
        };
        responses: {
            /** @description Reset completed and recorded in the administrative audit journal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new session token pair was issued in cookies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    signOutCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    signOutAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current account sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
