server {
    listen 80;
    access_log off;
    location /api/ { proxy_pass http://server:8080; proxy_set_header Host $host; }
    location / { proxy_pass http://frontend-app:3000; proxy_set_header Host $host; }
}
server {
    listen 81;
    access_log off;
    location /api/ { proxy_pass http://server:8080; proxy_set_header Host $host; }
    location / { proxy_pass http://frontend-admin:3000; proxy_set_header Host $host; }
}
