package tallyvane.identity.infrastructure.secondfactor

import com.google.crypto.tink.Aead
import com.google.crypto.tink.InsecureSecretKeyAccess
import com.google.crypto.tink.RegistryConfiguration
import com.google.crypto.tink.TinkJsonProtoKeysetFormat
import com.google.crypto.tink.aead.AeadConfig
import tallyvane.identity.application.port.SecretCipher
import tallyvane.identity.domain.secondfactor.EncryptedSecret
import tallyvane.platform.kernel.Secret
import java.util.Base64

/**
 * The real [SecretCipher] — AES-256-GCM through Tink, over a keyset supplied as configuration,
 * never generated by this class.
 *
 * [serializedKeyset] is the composition root's own secret, the same category as
 * [tallyvane.identity.application.port.TokenHasher.Hmac]'s pepper: a value this class reads, never
 * one it mints. Generating a fresh keyset is a one-time operational step
 * (`KeysetHandle.generateNew(PredefinedAeadParameters.AES256_GCM)`, serialized with
 * `TinkJsonProtoKeysetFormat.serializeKeyset`), deliberately kept out of any code path that also
 * runs in production — Tink's own documentation names mixing key generation with key use as the
 * mistake to avoid.
 *
 * `AeadConfig.register()` runs once, in [init], because Tink resolves a primitive through its own
 * global registry rather than a constructor argument — calling it more than once across every
 * instance this class ever creates is documented as safe.
 */
internal class TinkSecretCipher(serializedKeyset: Secret) : SecretCipher {
    init {
        AeadConfig.register()
    }

    private val aead: Aead =
        TinkJsonProtoKeysetFormat
            .parseKeyset(serializedKeyset.revealed(), InsecureSecretKeyAccess.get())
            .getPrimitive(RegistryConfiguration.get(), Aead::class.java)

    override fun encrypt(plaintext: Secret): EncryptedSecret {
        val ciphertext = aead.encrypt(plaintext.revealed().toByteArray(Charsets.UTF_8), ASSOCIATED_DATA)
        return EncryptedSecret(Base64.getEncoder().encodeToString(ciphertext))
    }

    override fun decrypt(ciphertext: EncryptedSecret): Secret {
        val bytes = Base64.getDecoder().decode(ciphertext.value)
        val plaintext = aead.decrypt(bytes, ASSOCIATED_DATA)
        return Secret(String(plaintext, Charsets.UTF_8))
    }

    private companion object {
        /**
         * Binds every ciphertext this class produces to what it is for, so a value stolen from a
         * different purpose under the same key cannot be replayed here even if it decrypted.
         * There is exactly one purpose today; the cost of naming it is one constant.
         *
         * No dot in this literal on purpose: `own-schema-only` reads any `"lowercase.rest"`
         * string in a module's own source as a claimed Postgres schema, and a qualifier this
         * class does not own would fail that check for a reason that has nothing to do with it.
         */
        val ASSOCIATED_DATA = "identity-totp-secret-v1".toByteArray(Charsets.UTF_8)
    }
}
