/**
 * Public API of `shared/api` — the typed client for `docs/openapi.yaml` (types generated by
 * `pnpm run api:generate`, ADR-064) and the chain of transports behind it.
 *
 * A feature holds an `Api` (from `useApi()` in a component) and calls `get`, `post`, `put`, `trigger`,
 * `delete`. Keys, failures and an ended session are handled behind it.
 */
export { Api, type CallOptions } from "./Api";
export { ApiProvider, useApi } from "./ApiProvider";
export { createApi, type ApiOptions } from "./createApi";
export { ProblemError, type ProblemKind } from "./ProblemError";
export { type ExpiredSessionHandler } from "./ReauthenticatingTransport";
export type { components } from "./generated/schema";
