import { createUseStrings } from "frontend-shared/i18n";

export const useAuthStrings = createUseStrings({ auth: {
    brand: "Tallyvane", theme: "Change color theme", light: "Light", dark: "Dark",
    productEyebrow: "YOUR JOB SEARCH, IN FOCUS", productTitle: "Make room for\nyour next move.",
    productDescription: "A considered space for the roles, conversations, and small next steps that move your search forward.",
    preview: "A glimpse of your workspace", today: "Today", nextStep: "ONE NEXT STEP",
    previewTask: "Prepare for your conversation", previewDetail: "Keep your notes and questions together.",
    pipeline: "Your pipeline", saved: "Saved", applied: "Applied", interview: "Interview",
    role: "Product designer", company: "Company you’re exploring", previewLabel: "Illustrative workspace · sample data",
    footer: "A little more clarity. One step at a time.", signIn: "Sign in", createAccount: "Create account",
    loginTitle: "Welcome back.", loginDescription: "Pick up where your search left off.",
    registerTitle: "Your next chapter starts here.", registerDescription: "Create a space for your job search.",
    email: "Email address", name: "Name (optional)", password: "Password", newPassword: "New password",
    currentPassword: "Current password", passwordHelp: "Use 15–128 characters. A memorable passphrase works well.",
    showPassword: "Show password", hidePassword: "Hide password", google: "Continue with Google",
    divider: "or use your email", emailCode: "Email me a sign-in code", usePassword: "Use my password",
    forgot: "Forgot password?", noAccount: "New to Tallyvane?", hasAccount: "Already have an account?",
    backLogin: "Back to sign in", continue: "Continue", verify: "Verify and continue", code: "Verification code",
    codeHelp: "Enter the six-digit code. You can paste it directly from your email.",
    verifyTitle: "Check your inbox.", verifyDescription: "Enter the code sent to {email}.",
    verifyRegisterDescription: "Verify your email to finish creating your account.",
    resend: "Send a new code", resendWait: "Resend in {seconds}s", sent: "A new code has been requested. Check your inbox.",
    forgotTitle: "Let’s get you back in.", forgotDescription: "Enter your email. If it matches an account, we’ll send a password reset code.",
    sendReset: "Send reset code", resetTitle: "Choose a new password.", resetDescription: "Enter your email code and a new password to recover your account.",
    reset: "Reset password", resetDone: "Your password has been reset. You can now sign in.",
    mfaTitle: "One more check.", mfaDescription: "Choose a verification method to finish signing in.",
    methodEmail: "Email code", methodEmailDescription: "Receive a verification code in your inbox.",
    methodTotp: "Authenticator app", methodTotpDescription: "Use the current code from your authenticator.",
    methodBackup: "Backup code", methodBackupDescription: "Use one of your saved, single-use recovery codes.",
    otherMethod: "Choose another method", backupInput: "Backup code", backupHelp: "Each backup code can only be used once.",
    totpHelp: "Enter the current six-digit code from your authenticator app.",
    enrollTitle: "Add an authenticator.", enrollDescription: "Protect your account with a code that changes every 30 seconds.",
    enrollRequired: "Your sign-in policy requires an authenticator before you can continue.",
    enrollStart: "Set up authenticator", scan: "1. Scan with your authenticator app", manual: "Or enter this setup key manually", copy: "Copy", copied: "Copied",
    confirmTitle: "2. Enter the code from your app", confirm: "Confirm authenticator", backupTitle: "Save your backup codes.",
    backupDescription: "Keep these somewhere safe outside this account. Each code works once if you lose access to your authenticator.",
    download: "Download codes", savedCodes: "I’ve saved my backup codes", finish: "Continue to workspace",
    oauthTitle: "Connecting with Google…", oauthDescription: "You’ll continue securely with Google, then return here.",
    oauthErrorTitle: "Google sign-in didn’t finish.", oauthErrorDescription: "The request was canceled, expired, or could not be verified. You can try again or use another sign-in method.",
    retryGoogle: "Try Google again", signedIn: "You’re signed in.", signedInDescription: "Your workspace is ready when you are.",
    missing: "This verification session is no longer available. Start again to receive a fresh code.",
    invalidResponse: "The server returned an unexpected authentication state. Please start again.",
    errorTitle: "We couldn’t complete that", back: "Back", security: "Account security", securityDescription: "Manage how you sign in and where you’re signed in.",
    methods: "Sign-in methods", sessions: "Active sessions", verified: "Verified", unverified: "Not verified", enabled: "Enabled", disabled: "Not enabled",
    changePassword: "Change password", passwordChanged: "Your password has been changed.", remove: "Remove", revoke: "Sign out session", logout: "Sign out", refresh: "Refresh",
    loading: "Loading account security…", noSessions: "No active sessions to display.", emailEnroll: "Enable email verification", emailConfirm: "Confirm email verification",
    confirmRemove: "Remove this verification method? You may need to enroll again to meet your sign-in policy.", cancel: "Cancel", removeConfirm: "Remove method",
    backupGenerate: "Generate new backup codes", backupWarning: "Generating new codes replaces your previous backup codes.",
    demo: "Authentication preview", demoDescription: "Local UI catalog. Sample data only; these controls never authenticate or change an account.", demoResult: "Preview action only. No request was sent.",
    demoSelect: "Preview screen", demoFailure: "Show error", demoBusy: "Show loading", demoNormal: "Normal state", demoMail: "alex@example.test",
} });
