import { createUseStrings } from "frontend-shared/i18n";

export const authStrings = {
    brand: "Tallyvane", theme: "Change color theme", light: "Light", dark: "Dark",
    productEyebrow: "YOUR JOB SEARCH, IN FOCUS", productTitle: "Make room for\nyour next move.",
    productDescription: "A considered space for the roles, conversations, and small next steps that move your search forward.",
    preview: "A glimpse of your workspace", today: "Today", nextStep: "ONE NEXT STEP",
    previewTask: "Prepare for your conversation", previewDetail: "Keep your notes and questions together.",
    pipeline: "Your pipeline", saved: "Saved", applied: "Applied", interview: "Interview",
    role: "Product designer", company: "Company you’re exploring", previewLabel: "Illustrative workspace · sample data",
    footer: "A little more clarity. One step at a time.", signIn: "Sign in", createAccount: "Create account",
    loginTitle: "Welcome back.", loginDescription: "Pick up where your search left off.",
    registerTitle: "Your next chapter starts here.", registerDescription: "Create a space for your job search.",
    email: "Email address", name: "Name (optional)", password: "Password", newPassword: "New password",
    currentPassword: "Current password", passwordHelp: "Use 15–128 characters. A memorable passphrase works well.",
    showPassword: "Show password", hidePassword: "Hide password", google: "Continue with Google",
    divider: "or use your email", emailCode: "Email me a sign-in code", usePassword: "Use my password",
    forgot: "Forgot password?", noAccount: "New to Tallyvane?", hasAccount: "Already have an account?",
    backLogin: "Back to sign in", continue: "Continue", verify: "Verify and continue", code: "Verification code",
    codeHelp: "Enter the six-digit code. You can paste it directly from your email.",
    verifyTitle: "Check your inbox.", verifyDescription: "Enter the code sent to {email}.",
    verifyRegisterDescription: "Verify your email to finish creating your account.",
    resend: "Send a new code", resendWait: "Resend in {seconds}s", sent: "A new code has been requested. Check your inbox.",
    forgotTitle: "Let’s get you back in.", forgotDescription: "Enter your email. If it matches an account, we’ll send a password reset code.",
    sendReset: "Send reset code", resetTitle: "Choose a new password.", resetDescription: "Enter your email code and a new password to recover your account.",
    reset: "Reset password", resetDone: "Your password has been reset. You can now sign in.",
    mfaTitle: "One more check.", mfaDescription: "Choose a verification method to finish signing in.",
    methodEmail: "Email code", methodEmailDescription: "Receive a verification code in your inbox.",
    methodTotp: "Authenticator app", methodTotpDescription: "Use the current code from your authenticator.",
    methodBackup: "Backup code", methodBackupDescription: "Use one of your saved, single-use recovery codes.",
    otherMethod: "Choose another method", backupInput: "Backup code", backupHelp: "Each backup code can only be used once.",
    totpHelp: "Enter the current six-digit code from your authenticator app.",
    enrollTitle: "Add an authenticator.", enrollDescription: "Protect your account with a code that changes every 30 seconds.",
    enrollRequired: "Your sign-in policy requires an authenticator before you can continue.",
    enrollStart: "Set up authenticator", scan: "1. Scan with your authenticator app", manual: "Or enter this setup key manually", copy: "Copy", copied: "Copied",
    confirmTitle: "2. Enter the code from your app", confirm: "Confirm authenticator", backupTitle: "Save your backup codes.",
    backupDescription: "Keep these somewhere safe outside this account. Each code works once if you lose access to your authenticator.",
    download: "Download codes", savedCodes: "I’ve saved my backup codes", finish: "Continue to workspace",
    oauthTitle: "Connecting with Google…", oauthDescription: "You’ll continue securely with Google, then return here.",
    oauthErrorTitle: "Google sign-in didn’t finish.", oauthErrorDescription: "The request was canceled, expired, or could not be verified. You can try again or use another sign-in method.",
    retryGoogle: "Try Google again", signedIn: "You’re signed in.", signedInDescription: "Your workspace is ready when you are.",
    missing: "This verification session is no longer available. Start again to receive a fresh code.",
    invalidResponse: "The server returned an unexpected authentication state. Please start again.",
    errorTitle: "We couldn’t complete that", back: "Back", security: "Account security", securityDescription: "Manage how you sign in and where you’re signed in.",
    methods: "Sign-in methods", sessions: "Active sessions", verified: "Verified", unverified: "Not verified", enabled: "Enabled", disabled: "Not enabled",
    changePassword: "Change password", passwordChanged: "Your password has been changed.", remove: "Remove", revoke: "Sign out session", logout: "Sign out", refresh: "Refresh",
    loading: "Loading account security…", noSessions: "No active sessions to display.", emailEnroll: "Enable email verification", emailConfirm: "Confirm email verification",
    confirmRemove: "Remove this verification method? You may need to enroll again to meet your sign-in policy.", cancel: "Cancel", removeConfirm: "Remove method",
    backupGenerate: "Generate new backup codes", backupWarning: "Generating new codes replaces your previous backup codes.",
    demo: "Authentication preview", demoDescription: "Local UI catalog. Sample data only; these controls never authenticate or change an account.", demoResult: "Preview action only. No request was sent.",
    demoSelect: "Preview screen", demoFailure: "Show error", demoBusy: "Show loading", demoNormal: "Normal state", demoMail: "alex@example.test",
    mfaTitleHelp: "Use one of the verification methods available to your account.",
    sendEmailMfaCode: "Send email code", mfaEmailCodeSent: "MFA code sent",
    mfaEmailCodeDescription: "Check your inbox for an MFA code.",
    enrollmentDescription: "Scan this code with an authenticator app, then confirm the current code.",
    forgotHelp: "Password recovery is available when email challenges are configured on this server.",
    otpHelp: "Email sign-in and verification codes are available when email challenges are configured.",
    googleAvailableHelp: "Google sign-in becomes available after the server OAuth client is configured.",
    callbackDescription: "This page will show the result of a configured OAuth callback.",
    previewDescription: "Explore the connected page layouts and interaction states.",
    googleCancelled: "Google sign-in cancelled", googleFailed: "Google sign-in failed",
    alternateSignInHelp: "Check your account or try another sign-in method.",
    unknownAuthStep: "The server returned an unrecognized authentication step.",
    authFailed: "Authentication failed", delayedMail: "Email delivery is delayed. You can request another verification code here.",
    accountCreated: "Account created", signInExpired: "Your sign-in check has expired. Start again to sign in.",
    authenticatorEnabled: "Authenticator enabled", authenticatorEnabledDescription: "Your account is now protected with an authenticator app.",
    authenticatorConfirmed: "Authenticator confirmed. Your account is protected.",
    requiredAuthenticatorEnabledDescription: "Your authenticator is enrolled. Sign in again to continue.",
    requiredAuthenticatorConfirmed: "Authenticator enrolled. Sign in again to continue.",
    checkInboxForCode: "Check {email} for your six-digit code.", signInCodeSent: "Sign-in code sent",
    signInContinuedError: "Sign-in could not continue", emailVerified: "Email verified",
    emailVerifiedDescription: "Your account email has been confirmed.", emailVerifiedNotice: "Your email is verified. You can now sign in.",
    requestNewCodeFirst: "Request a new verification code before entering a code.",
    resetCodeSent: "Reset code sent", resetCodeNeutral: "If an account uses this address, a reset code has been sent. It expires in 10 minutes.",
    passwordUpdated: "Password updated", passwordUpdatedDescription: "You can now sign in with your new password.",
    passwordUpdatedNotice: "Your password has been updated. Your authenticator and other second-factor requirements remain in place.",
    changePasswordAction: "Change password",
    recoveryCodesTitle: "Recovery codes",
    confirmPassword: "Confirm your password",
    recoveryCodesIssued: "Recovery codes generated",
    recoveryCodesOneTime: "Save these codes now. They are shown only once, and generating another set invalidates this one.",
    backupCodesSaved: "I’ve saved these codes",
    sessionRevoked: "Session signed out",
    sessionRevokeFailed: "Could not sign out this session",
    securityLoadFailed: "Could not load account security",
    emailMfaTitle: "Email verification",
    emailMfaDescription: "Add email as a second factor. We’ll confirm your address before enabling it.",
    emailMfaPassword: "Email MFA password",
    emailMfaCode: "Email MFA code",
    emailMfaEnable: "Enable email verification",
    emailMfaConfirm: "Confirm email verification",
    emailMfaCodeSent: "Verification code sent",
    emailMfaCodeSentHelp: "Enter the six-digit code sent to your account email.",
    emailMfaEnabled: "Email verification enabled",
    emailMfaEnabledNotice: "Email verification enabled.",
    factorManagementTitle: "Second-factor methods",
    factorManagementDescription: "Add or remove the checks used to protect your sign-ins.",
    factorAuthenticator: "Authenticator app",
    factorEmail: "Email code",
    factorBackup: "Recovery codes",
    recentReauthenticationReady: "Your identity was verified in the last five minutes.",
    recentReauthenticationNeeded: "Verify your identity before changing a second factor.",
    noEnrolledFactors: "No second factors are enrolled yet.",
    reauthenticateWithPassword: "Verify with password",
    reauthPasswordLabel: "Password to verify your identity",
    reauthenticateWithGoogle: "Verify with Google",
    reauthenticated: "Identity verified",
    reauthFailed: "Could not verify your identity",
    reauthTryAgain: "Check your password or choose Google if it is linked to this account.",
    reauthenticationRequired: "Verify your identity again before changing MFA",
    factorDisabled: "Removed {factor}",
    factorRequiredByPolicy: "This factor is required by your sign-in policy",
    factorDisableFailed: "Could not remove this second factor",
    factorEnrollmentFailed: "Could not enroll this factor",
    disableFactorTitle: "Remove this second factor?",
    disableFactorDescription: "You may need to enroll another factor to meet your sign-in policy. This change needs recent identity verification.",
    disableFactorConfirm: "Remove second factor",
    copyFailed: "Could not copy the setup key",
    lastUsed: "Last active {date}",
    resendNeutralTitle: "Check your email", resendNeutralDescription: "If this account is waiting for verification, a new code has been sent.",
    resendFailed: "Could not resend the code", registrationCodeSent: "Enter the six-digit code sent to {email}.",
    resendCodeIn: "Resend code in {seconds}s", resendVerificationCode: "Resend verification code",
    preparingVerification: "Preparing your verification step…", useDifferentEmail: "Use a different email",
    emailDisclosure: "Continue with email", emailDisclosureHelp: "Create your account with an email address and password",
    emailCodePreviewHelp: "Email-code sign-in and password recovery are shown in the preview. They require the email challenge service to be enabled.",
    networkError: "We couldn’t reach the server. Check your connection and try again.",
    sessionExpiredError: "Your session has expired. Sign in again.",
    securitySessionError: "A secure session could not be started. Refresh and try again.",
    rateLimitedError: "Too many attempts. Wait a little and try again.",
    invalidEmail: "Enter a valid email address.",
    invalidPassword: "Check this password and try again.",
    invalidCode: "Enter a valid verification code.",
    invalidField: "Check this value and try again.",
    notConfigured: "Not configured", verificationMethod: "Verification method", authenticatorCode: "Authenticator code",
    emailCodeLabel: "Email code", backupCodeLabel: "Backup code", codeFromAuthenticator: "Code from your authenticator",
    addUriManually: "Add this URI manually in your authenticator app:", confirmAuthenticator: "Confirm authenticator",
    authenticatorQr: "Authenticator setup QR code", manualSetupKey: "Or enter this setup key manually",
    qrUnavailable: "The QR code could not be displayed. Use the manual setup key below.",
    previewOnly: "Preview only.", previewCatalogHelp: "Use the selector above to inspect each planned screen. Actions in this catalog never send credentials or modify an account.",
    googleNotConfigured: "Google sign-in is not configured on this server yet.", verificationCodeSentTo: "Enter the six-digit code sent to {email}.",
    verifyEmail: "Verify email", enterCodeDescription: "Enter the six-digit code sent to {email}.",
    emailCodeWithPassword: "Email me a sign-in code", continueWithGoogle: "Continue with Google",
    verifyAndContinue: "Verify and continue", createAccountAction: "Create account",
    sendResetCode: "Send reset code", resetPassword: "Reset password", returnToSignIn: "Return to sign in",
    genericContinue: "Continue", previewFlowHelp: "This page is an interactive UI preview. The matching server flow is not configured yet.",
    previewScreen: "Preview screen", openPreview: "Open authentication preview",
    previewActionNotice: "This flow is shown in the UI preview. No request was sent to the server.",
    noAccountPrompt: "New to Tallyvane?", hasAccountPrompt: "Already have an account?",
    createAccountLink: "Create an account", signInLink: "Sign in", forgotPasswordLink: "Forgot password?",
    signInEmailCodeLink: "Sign in with an email code",
    callbackChecking: "Checking the OAuth response…", requestFailed: "We couldn’t complete that request. Please try again.",
    requestFailedTitle: "We couldn’t complete that", backToPrevious: "Back",
    googleAccountTitle: "Google sign-in", googleConnected: "Google is connected to this account.",
    googleNotConnected: "Connect Google after confirming your password.", linkGoogle: "Connect Google",
    unlinkGoogle: "Disconnect Google", unlinkGoogleTitle: "Disconnect Google?",
    unlinkGoogleDescription: "Confirm with your password. You need another sign-in method to disconnect Google.",
    unlinkGoogleConfirm: "Disconnect account", googleLinkedToast: "Google account connected",
    googleUnlinkedToast: "Google account disconnected", googleLinkFailed: "Could not update Google sign-in",
    lastSignInMethod: "Add another sign-in method before disconnecting Google.",
} as const;

export type AuthStringKey = keyof typeof authStrings;
export const useAuthStrings = createUseStrings({ auth: authStrings });
