import { createUseStrings } from "frontend-shared/i18n";

const dictionary = {
    adminLogin: {
        brand: "Tallyvane",
        title: "Sign in to administration",
        description: "Use your administrator account to continue.",
        email: "Email address",
        password: "Password",
        signIn: "Sign in",
        continueWithGoogle: "Continue with Google",
        googleSignInFailed: "Google sign-in did not finish. Try again or use another available method.",
        signInOptionsUnavailable: "No supported sign-in method is currently available.",
        useEmailCode: "Sign in with an email code",
        usePassword: "Use my password",
        emailSignInCodeSent: "A sign-in code was sent to your email.",
        checkingAccess: "Checking administrator access…",
        checkingSession: "Checking your session…",
        completingSignIn: "Completing administrator sign-in…",
        accessDeniedTitle: "Administrator access required",
        accessDenied: "This account does not have administrator access.",
        tryAnotherAccount: "Sign in with another account",
        requestFailed: "We could not complete the request. Please try again.",
        networkError: "Could not connect. Check your connection and try again.",
        invalidCredentials: "Email or password is incorrect.",
        invalidCode: "That code could not be verified. Check it and try again.",
        signInExpired: "The sign-in check expired. Please sign in again.",
        rateLimited: "There have been too many attempts. Wait a moment and try again.",
        verificationTitle: "Verify it’s you",
        verificationDescription: "Choose a verification method enabled for your account.",
        methodTotp: "Authenticator app",
        methodEmail: "Email code",
        signInAnotherWay: "Sign in another way",
        hideOtherMethods: "Hide other methods",
        verificationCode: "Verification code",
        sendEmailCode: "Send email code",
        emailCodeSent: "A verification code was sent to your email.",
        verifyAndContinue: "Verify and continue",
        backToSignIn: "Back to sign in",
        retry: "Try again",
        showPassword: "Show password",
        hidePassword: "Hide password",
        lightTheme: "Use light theme",
        darkTheme: "Use dark theme",
        light: "Light",
        dark: "Dark",
        stepUpTitle: "Confirm your identity",
        stepUpDescription: "This action needs another identity check. Complete it, return to the action, and submit it again.",
        stepUpUnavailable: "No supported identity check is available for this action in the admin app.",
        stepUpLoadFailed: "Could not load identity checks. Try again.",
        stepUpSendCode: "Send verification code",
        stepUpSubmit: "Confirm identity",
        stepUpCodeSent: "A verification code was sent.",
        stepUpRank: "Assurance level {rank}",
        stepUpGoogle: "Verify with Google",
        stepUpGoogleReady: "Google identity is verified.",
        stepUpGoogleFailed: "Google verification did not finish. Try again.",
        actionAccessDenied: "Your account is signed in, but this action is not available to it.",
        close: "Close",
    },
} as const;

export const useAdminLoginStrings = createUseStrings(dictionary);
