import { createUseStrings } from "frontend-shared/i18n";

const dictionary = {
    adminLogin: {
        brand: "Tallyvane",
        title: "Sign in to administration",
        description: "Use your administrator account to continue.",
        email: "Email address",
        password: "Password",
        signIn: "Sign in",
        checkingAccess: "Checking administrator access…",
        checkingSession: "Checking your session…",
        accessDeniedTitle: "Administrator access required",
        accessDenied: "This account does not have administrator access.",
        tryAnotherAccount: "Sign in with another account",
        requestFailed: "We could not complete the request. Please try again.",
        networkError: "Could not connect. Check your connection and try again.",
        invalidCredentials: "Email or password is incorrect.",
        invalidCode: "That code could not be verified. Check it and try again.",
        rateLimited: "There have been too many attempts. Wait a moment and try again.",
        verificationTitle: "Verify it’s you",
        verificationDescription: "Choose a verification method enabled for your account.",
        methodTotp: "Authenticator app",
        methodEmail: "Email code",
        methodBackup: "Backup code",
        verificationCode: "Verification code",
        sendEmailCode: "Send email code",
        emailCodeSent: "A verification code was sent to your email.",
        verifyAndContinue: "Verify and continue",
        backToSignIn: "Back to sign in",
        enrollmentTitle: "Set up an authenticator",
        enrollmentDescription: "Add this account to your authenticator app with the setup key, then enter its six-digit code.",
        enrollmentStart: "Create setup key",
        manualSetupKey: "Setup key",
        enrollmentCode: "Code from authenticator app",
        confirmEnrollment: "Confirm setup",
        enrollmentComplete: "Authenticator set up. Sign in again with your password, then verify with the new code.",
        retry: "Try again",
        showPassword: "Show password",
        hidePassword: "Hide password",
        lightTheme: "Use light theme",
        darkTheme: "Use dark theme",
        light: "Light",
        dark: "Dark",
        requiredMethodUnavailable: "This sign-in policy requires a setup method that is not supported on this screen.",
        preparingEnrollment: "Preparing your authenticator setup key…",
    },
} as const;

export const useAdminLoginStrings = createUseStrings(dictionary);
